### PR TITLE
Paiva x/feature/ci2-cris-5/manage-projects

### LINKED ISSUE #21: Develop base UI
- Develop a base template for the application that includes headers, footers?, navigation bars, etc.

### PR DESCRIPTION
**Pull request by PaivaX**
Closes #21, #5 

Homepage 100% funcional;
secção dos projetos 90% funcional.
Com o decorrer do projeto, faço os restantes ajustes.

### CODE REVIEW

**Review by curiousyigit — CHANGES_REQUESTED** [review]
Please change the PR name and the branch name to be inline with our conventions

**Review by curiousyigit — CHANGES_REQUESTED** [review]
You need either rebase to or merge the latest changes to your branch from main

**Review by curiousyigit — CHANGES_REQUESTED** [review]
image

This is strange. Why have these files changed their meta data?

Could it be related to this?
https://sesync-ci.github.io/faq/why-does-git-show-that-all-my-files-changed-even-though-i-didn't-change-them.html

I'm not sure if we need to fix this, but if we merge without being sure it may break the repo

**Comment by PaivaX** [comment]
> Please change the PR name and the branch name to be inline with our conventions

done

**Pull request closed without merging**
